<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 60px 40px 50px 40px; }
        body { font-family: DejaVu Sans, sans-serif; color: #1f2933; font-size: 11px; line-height: 1.5; }
        .letterhead { text-align: center; border-bottom: 2px solid #4c1d95; padding-bottom: 12px; margin-bottom: 20px; }
        .letterhead .school-name { font-size: 18px; font-weight: bold; color: #4c1d95; margin: 0; }
        .letterhead .school-meta { font-size: 10px; color: #52606d; margin-top: 4px; }
        .title { text-align: center; font-size: 15px; font-weight: bold; margin: 10px 0 4px 0; }
        .subtitle { text-align: center; font-size: 10px; color: #52606d; margin: 0 0 20px 0; }
        table.data { width: 100%; border-collapse: collapse; }
        table.data th { background: #4c1d95; color: #fff; text-align: left; padding: 6px 8px; font-size: 10px; }
        table.data td { padding: 5px 8px; border-bottom: 1px solid #e4e7eb; font-size: 10px; }
        table.data tr:nth-child(even) td { background: #f5f3ff; }
        .footer { position: fixed; bottom: -35px; left: 0; right: 0; text-align: center; font-size: 8px; color: #9aa5b1; }
    </style>
</head>
<body>
    <div class="letterhead">
        <p class="school-name">{{ $school->name }}</p>
        <p class="school-meta">
            {{ collect([$school->address, $school->city, $school->country])->filter()->join(', ') }}
        </p>
    </div>

    <p class="title">{{ $title }}</p>
    <p class="subtitle">Generated by {{ $generatedBy }} on {{ now()->toFormattedDateString() }}</p>

    <table class="data">
        <thead>
            <tr>
                <th>Day</th>
                <th>Time</th>
                <th>Subject</th>
                <th>Class</th>
                <th>Teacher</th>
                <th>Room</th>
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $row)
                <tr>
                    <td>{{ $row['day_of_week'] }}</td>
                    <td>{{ $row['start_time'] }} – {{ $row['end_time'] }}</td>
                    <td>{{ $row['subject'] ?? '—' }}</td>
                    <td>{{ $row['class_name'] ?? '—' }}</td>
                    <td>{{ $row['teacher'] ?? '—' }}</td>
                    <td>{{ $row['room'] ?? '—' }}</td>
                </tr>
            @empty
                <tr><td colspan="6" style="text-align:center; padding: 16px;">No timetable entries found.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by SchoolHub &middot; Confidential — for authorized school use only</div>
</body>
</html>
