<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 70px 60px; }
        body { font-family: DejaVu Sans, sans-serif; color: #1f2933; font-size: 13px; line-height: 1.6; }
        .letterhead { text-align: center; border-bottom: 2px solid #4c1d95; padding-bottom: 16px; margin-bottom: 32px; }
        .letterhead .school-name { font-size: 22px; font-weight: bold; color: #4c1d95; margin: 0; }
        .letterhead .school-meta { font-size: 11px; color: #52606d; margin-top: 4px; }
        .title { text-align: center; font-size: 20px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; margin: 28px 0; }
        .body-text { font-size: 14px; text-align: center; margin: 0 30px; }
        .body-text strong { color: #4c1d95; }
        .meta-table { width: 100%; margin: 36px 0; }
        .meta-table td { padding: 4px 0; font-size: 12px; }
        .meta-table td.label { color: #52606d; width: 180px; }
        .signature { margin-top: 70px; width: 260px; }
        .signature .line { border-top: 1px solid #1f2933; margin-bottom: 4px; }
        .footer { position: fixed; bottom: -40px; left: 0; right: 0; text-align: center; font-size: 9px; color: #9aa5b1; }
    </style>
</head>
<body>
    <div class="letterhead">
        <p class="school-name">{{ $school->name }}</p>
        <p class="school-meta">
            {{ collect([$school->address, $school->city, $school->country])->filter()->join(', ') }}
            @if($school->email) &middot; {{ $school->email }} @endif
        </p>
    </div>

    <p class="title">{{ $certificateTitle }}</p>

    <p class="body-text">
        This is to certify that <strong>{{ $student->full_name }}</strong>
        (Admission No. {{ $student->admission_number }})
        @if($className)
            was enrolled in <strong>{{ $className }}</strong>
        @endif
        @if($academicYearName)
            during the <strong>{{ $academicYearName }}</strong> academic year
        @endif
        at {{ $school->name }}.
    </p>

    <table class="meta-table">
        <tr>
            <td class="label">Student name</td>
            <td>{{ $student->full_name }}</td>
        </tr>
        <tr>
            <td class="label">Admission number</td>
            <td>{{ $student->admission_number }}</td>
        </tr>
        <tr>
            <td class="label">Class</td>
            <td>{{ $className ?? '—' }}</td>
        </tr>
        <tr>
            <td class="label">Academic year</td>
            <td>{{ $academicYearName ?? '—' }}</td>
        </tr>
        <tr>
            <td class="label">Date issued</td>
            <td>{{ now()->toFormattedDateString() }}</td>
        </tr>
    </table>

    <div class="signature">
        <div class="line"></div>
        <p>Authorized signatory, {{ $school->name }}</p>
    </div>

    <div class="footer">Generated by SchoolHub Africa &middot; Verification code: {{ $student->qr_code }}</div>
</body>
</html>
