<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 70px 60px; }
        body { font-family: DejaVu Sans, sans-serif; color: #1f2933; font-size: 13px; line-height: 1.6; }
        .letterhead { text-align: center; border-bottom: 2px solid #4c1d95; padding-bottom: 16px; margin-bottom: 28px; }
        .letterhead .school-name { font-size: 22px; font-weight: bold; color: #4c1d95; margin: 0; }
        .letterhead .school-meta { font-size: 11px; color: #52606d; margin-top: 4px; }
        .title { text-align: center; font-size: 18px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; margin: 24px 0; }
        .meta-table { width: 100%; margin: 20px 0; }
        .meta-table td { padding: 4px 0; font-size: 12px; }
        .meta-table td.label { color: #52606d; width: 180px; }
        .body-text { margin: 20px 0; }
        .signature-row { width: 100%; margin-top: 70px; }
        .signature-row td { width: 50%; vertical-align: top; }
        .signature .line { border-top: 1px solid #1f2933; margin-bottom: 4px; width: 220px; }
        .footer { position: fixed; bottom: -40px; left: 0; right: 0; text-align: center; font-size: 9px; color: #9aa5b1; }
    </style>
</head>
<body>
    <div class="letterhead">
        <p class="school-name">{{ $school->name }}</p>
        <p class="school-meta">
            {{ collect([$school->address, $school->city, $school->country])->filter()->join(', ') }}
            @if($school->email) &middot; {{ $school->email }} @endif
        </p>
    </div>

    <p class="title">Contract of Employment</p>

    <table class="meta-table">
        <tr>
            <td class="label">Employee name</td>
            <td>{{ $contract->user->name }}</td>
        </tr>
        <tr>
            <td class="label">Job title</td>
            <td>{{ $jobTitle ?? '—' }}</td>
        </tr>
        <tr>
            <td class="label">Contract type</td>
            <td>{{ ucfirst(str_replace('_', ' ', $contract->contract_type)) }}</td>
        </tr>
        <tr>
            <td class="label">Start date</td>
            <td>{{ $contract->start_date?->toFormattedDateString() }}</td>
        </tr>
        <tr>
            <td class="label">End date</td>
            <td>{{ $contract->end_date?->toFormattedDateString() ?? 'Ongoing' }}</td>
        </tr>
        <tr>
            <td class="label">Salary</td>
            <td>{{ number_format((float) $contract->salary, 2) }} {{ $school->currency }}</td>
        </tr>
    </table>

    <p class="body-text">
        This contract confirms the terms of employment of <strong>{{ $contract->user->name }}</strong>
        with {{ $school->name }} as outlined above.
        @if($contract->notes)
            <br><br>{{ $contract->notes }}
        @endif
    </p>

    <table class="signature-row">
        <tr>
            <td>
                <div class="signature">
                    <div class="line"></div>
                    <p>Employer signature, {{ $school->name }}</p>
                </div>
            </td>
            <td>
                <div class="signature">
                    <div class="line"></div>
                    <p>Employee signature, {{ $contract->user->name }}</p>
                </div>
            </td>
        </tr>
    </table>

    <div class="footer">Generated by SchoolHub Africa on {{ now()->toFormattedDateString() }}</div>
</body>
</html>
