<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { size: A4 landscape; margin: 40px 40px; }
        body { font-family: DejaVu Sans, sans-serif; color: #1f2933; font-size: 11px; line-height: 1.5; }
        .letterhead { text-align: center; border-bottom: 2px solid #4c1d95; padding-bottom: 14px; margin-bottom: 18px; }
        .letterhead .school-name { font-size: 20px; font-weight: bold; color: #4c1d95; margin: 0; }
        .letterhead .school-meta { font-size: 10px; color: #52606d; margin-top: 4px; }
        .title { text-align: center; font-size: 16px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; margin: 16px 0 4px; }
        .subtitle { text-align: center; font-size: 11px; color: #52606d; margin: 0 0 18px; }
        table.data { width: 100%; border-collapse: collapse; }
        table.data th, table.data td { border: 1px solid #cbd2d9; padding: 6px 8px; font-size: 10.5px; text-align: left; }
        table.data th { background: #f5f3ff; }
        .amount, .center { text-align: right; }
        .center { text-align: center; }
        .status { text-transform: capitalize; }
        tfoot td { font-weight: bold; background: #f5f3ff; }
        .footer { position: fixed; bottom: -30px; left: 0; right: 0; text-align: center; font-size: 9px; color: #9aa5b1; }
    </style>
</head>
<body>
    <div class="letterhead">
        @include('components.school-logo')
        <p class="school-name">{{ $school->name }}</p>
        <p class="school-meta">
            {{ collect([$school->address, $school->city, $school->country])->filter()->join(', ') }}
        </p>
    </div>

    <p class="title">Fee Report</p>
    <p class="subtitle">
        Status: {{ $status ? ucfirst($status) : 'All' }} &middot; Generated {{ now()->toFormattedDateString() }}
        &middot; {{ $invoices->count() }} invoice(s)
    </p>

    <table class="data">
        <thead>
            <tr>
                <th>Invoice #</th>
                <th>Student</th>
                <th>Admission #</th>
                <th class="amount">Total</th>
                <th class="amount">Paid</th>
                <th class="amount">Balance</th>
                <th class="center">Status</th>
                <th>Due date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($invoices as $invoice)
                <tr>
                    <td>{{ $invoice->invoice_number }}</td>
                    <td>{{ $invoice->student?->full_name ?? '—' }}</td>
                    <td>{{ $invoice->student?->admission_number ?? '—' }}</td>
                    <td class="amount">{{ number_format($invoice->total_amount, 2) }}</td>
                    <td class="amount">{{ number_format($invoice->amount_paid, 2) }}</td>
                    <td class="amount">{{ number_format($invoice->balance, 2) }}</td>
                    <td class="center status">{{ $invoice->status }}</td>
                    <td>{{ $invoice->due_date?->toFormattedDateString() ?? '—' }}</td>
                </tr>
            @empty
                <tr><td colspan="8" class="center">No invoices match this filter.</td></tr>
            @endforelse
        </tbody>
        @if($invoices->isNotEmpty())
            <tfoot>
                <tr>
                    <td colspan="3">Total</td>
                    <td class="amount">{{ number_format($totals['total_amount'], 2) }}</td>
                    <td class="amount">{{ number_format($totals['amount_paid'], 2) }}</td>
                    <td class="amount">{{ number_format($totals['balance'], 2) }}</td>
                    <td colspan="2"></td>
                </tr>
            </tfoot>
        @endif
    </table>

    <div class="footer">Generated by SchoolHub Africa &middot; {{ $school->name }}</div>
</body>
</html>
