<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 60px 50px; }
        body { font-family: DejaVu Sans, sans-serif; color: #1f2933; font-size: 12px; line-height: 1.5; }
        .letterhead { text-align: center; border-bottom: 2px solid #4c1d95; padding-bottom: 14px; margin-bottom: 20px; }
        .letterhead .school-name { font-size: 20px; font-weight: bold; color: #4c1d95; margin: 0; }
        .letterhead .school-meta { font-size: 10px; color: #52606d; margin-top: 4px; }
        .title { text-align: center; font-size: 16px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; margin: 18px 0; }
        .meta-table { width: 100%; margin-bottom: 20px; }
        .meta-table td { padding: 2px 0; font-size: 11px; }
        .meta-table td.label { color: #52606d; width: 140px; }
        .exam-block { margin-bottom: 22px; page-break-inside: avoid; }
        .exam-block h3 { font-size: 13px; margin: 0 0 6px; color: #4c1d95; }
        table.data { width: 100%; border-collapse: collapse; }
        table.data th, table.data td { border: 1px solid #cbd2d9; padding: 5px 8px; font-size: 11px; text-align: left; }
        table.data th { background: #f5f3ff; }
        .summary-row td { font-weight: bold; background: #fafafa; }
        .footer { position: fixed; bottom: -40px; left: 0; right: 0; text-align: center; font-size: 9px; color: #9aa5b1; }
    </style>
</head>
<body>
    <div class="letterhead">
        <p class="school-name">{{ $school->name }}</p>
        <p class="school-meta">
            {{ collect([$school->address, $school->city, $school->country])->filter()->join(', ') }}
        </p>
    </div>

    <p class="title">Academic Transcript</p>

    <table class="meta-table">
        <tr>
            <td class="label">Student name</td>
            <td>{{ $student->full_name }}</td>
        </tr>
        <tr>
            <td class="label">Admission number</td>
            <td>{{ $student->admission_number }}</td>
        </tr>
        <tr>
            <td class="label">Date issued</td>
            <td>{{ now()->toFormattedDateString() }}</td>
        </tr>
    </table>

    @forelse($exams as $exam)
        <div class="exam-block">
            <h3>{{ $exam['exam_name'] }} &mdash; {{ $exam['academic_year_name'] }}@if($exam['term_name']) ({{ $exam['term_name'] }})@endif</h3>
            <table class="data">
                <thead>
                    <tr>
                        <th>Subject</th>
                        <th>Marks obtained</th>
                        <th>Max marks</th>
                        <th>Grade</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($exam['subjects'] as $subject)
                        <tr>
                            <td>{{ $subject['subject_name'] }}</td>
                            <td>{{ $subject['marks_obtained'] ?? '—' }}</td>
                            <td>{{ $subject['max_marks'] }}</td>
                            <td>{{ $subject['grade'] ?? '—' }}</td>
                        </tr>
                    @endforeach
                    <tr class="summary-row">
                        <td>Overall</td>
                        <td colspan="2">{{ $exam['average_percentage'] !== null ? $exam['average_percentage'] . '%' : '—' }}</td>
                        <td>{{ $exam['overall_grade'] ?? '—' }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    @empty
        <p>No exam results recorded for this student yet.</p>
    @endforelse

    <div class="footer">Generated by SchoolHub Africa &middot; Verification code: {{ $student->qr_code }}</div>
</body>
</html>
